baseurl = "/"
languageCode = "zh-cn"
theme = "hugo-theme-stack"
paginate = 5
title = "SROTIY"
disqusShortname = "Srotiy"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "zh"                   # Theme i18n support

[permalinks]
    post = "/posts/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    rssFullContent = true
    [params.dateFormat]
        published = "2006-01-02"
        lastUpdated = "Jan 02, 2006 15:04 MST"
    [params.sidebar]
        emoji = "🩰"
        avatar = "img/srotiy.jpeg"
        subtitle = "呐"
    [params.article]
        math = false
        [params.article.license]
            enabled = true 
            default = "Licenced under CC BY-NC-SA 4.0"
    [params.comments]
        enabled = false
        # Only Disqus is available so far
        provider = "disqus"
    [params.widgets]
        enabled = ['archives']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "posts"       
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
    [params.defaultImage]
        [params.defaultImage.article]
            enabled = false
            local = false
            src = ""
        [params.defaultImage.articleList]
            enabled = false
            local = true
            src = ""
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "主页"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about-cn"
        name = "关于"
        url = "about"
        weight = -90
        pre = "user"
[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = false
    [markup.goldmark.renderer]
        unsafe = true
